### PR TITLE
Added boolean type scopes

### PR DESCRIPTION
**Pull request by dmitry-ilyashevich**

### CODE REVIEW

**Comment by dmitry-ilyashevich** [comment]
Inspired by #1

**Comment by alexisbernard** [comment]
Nice ! I like the suffix / prefix stuff :+1: 

Just one remark, since in Ruby the convention is to return a boolean when the method name ends with a question mark. But in our case it returns a scope, so it seems more consistent to have just: `Transaction.non_profit` instead of `Transaction.non_profit?`.

Except this small detail I would be happy to merge it :)

**Comment by dmitry-ilyashevich** [comment]
Fixed, thanks for quick reply!

**Comment by alexisbernard** [comment]
It has been published in the 0.3.0.

**Pull request merged**
